#!/usr/bin/env python3

import os
import re
import sys
import time
import argparse
import platform
import netifaces
from termcolor import cprint
from colorama import Fore, Style
from netifaces import interfaces, ifaddresses, AF_INET

ok = Fore.LIGHTGREEN_EX + '[+]' + Style.RESET_ALL
err = Fore.LIGHTRED_EX + '[!]' + Style.RESET_ALL
info = Fore.LIGHTYELLOW_EX + '[*]' + Style.RESET_ALL

if sys.version_info.major != 3:
    print('\n' + err + ''' please run this script with python3.
    usage: python3 inumaki.py <args> \n''')
    sys.exit(1)

print('\n' + info, 'platform detected: {}'.format(platform.system()))


def clear():
    time.sleep(0.5)
    if platform.system() == 'Linux':
        os.system('clear')
    else:
        # os.system('cls') there's literally no point to this yet, this script isn't compatible with windows for now.
        print(err, 'this script only works on linux. for now... sorry about that! :(')
        sys.exit(1)


def banner():
    print(Fore.LIGHTMAGENTA_EX + '''\
     |\_/|
     | @ @   inumaki! (cli shell generator) v1.0
     |   <>              _
     |  _/\------____ ((| |))    by cr0w
     |               `--' |
 ____|_       ___|   |___.'
/_/_____/____/_______|
''' + Style.RESET_ALL)


def init():
    clear()
    banner()


def inetfaces():
    print(info, 'getting interfaces for lhost population...')
    time.sleep(0.3)
    print(ok, netifaces.interfaces())
    ips = []
    for interface in interfaces():
        for link in ifaddresses(interface)[AF_INET]:
            ips.append(link['addr'])
            print(ok, Fore.LIGHTYELLOW_EX + link['addr'], Style.RESET_ALL)


def submitlhost():
    global lhost
    print(info, 'getting lhost submission')
    print(info, 'which address would you like to create a reverse shell for?')
    while True:
        try:
            lhost = input('\n\rcr0w > ')
            if re.match(r'^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$', lhost):
                print('\n' + ok, 'lhost set to: {}'.format(Fore.LIGHTYELLOW_EX + lhost))
                return lhost
            else:
                print('\n' + err, 'please enter one of the addresses above.')
                print(err, 'example:' + Fore.LIGHTYELLOW_EX, 'cr0w >', Fore.LIGHTRED_EX + '192.168.0.1',
                      Style.RESET_ALL)
        except:
            print('\n\n' + err, 'exception caught! exiting...\n')
            sys.exit(1)


def submitlport():
    global lport
    init()
    print('\n' + ok, 'lhost set to: {}'.format(Fore.LIGHTYELLOW_EX + lhost))
    print('\n' + info, 'getting port submission')
    print(info, 'please specify a port for the connect back')
    while True:
        try:
            lport = input('\n\rcr0w > ')
            integer = lport.isdigit()
            if integer:
                print('\n' + ok, 'lport set to: {}'.format(Fore.LIGHTYELLOW_EX + lport))
                return lport
            else:
                print('\n' + err, 'please enter a port')
                print(err, 'example:' + Fore.LIGHTYELLOW_EX, 'cr0w >', Fore.LIGHTRED_EX + '9999',
                      Style.RESET_ALL)
        except:
            print('\n\n' + err, 'exception caught! exiting...\n')
            sys.exit(1)


def showcurrentconfig():
    init()
    print('\n' + ok + Fore.LIGHTYELLOW_EX, 'lhost, lport', Style.RESET_ALL +
          'is set to {}:{}'.format(Fore.LIGHTRED_EX + lhost, lport) + '\n' + Style.RESET_ALL)


def gettypeofshell():
    global shelltype
    print(info, 'getting shell submission')
    print(info, 'which type of shell would you like to use?')
    print(info, 'the following shells are currently compatible', Fore.LIGHTRED_EX + '''\r
    
    POWERSHELL
    PYTHON3
    PYTHON
    BASH
    PERL
    RUBY
    LUA
    PHP
    SH
    NC''', Style.RESET_ALL)

    while True:
        try:
            acceptedshells = ['POWERSHELL',
                              'PYTHON3',
                              'PYTHON',
                              'BASH',
                              'PERL',
                              'RUBY',
                              'LUA',
                              'PHP',
                              'SH',
                              'NC']
            shelltype = input('\n\rcr0w > ')
            if shelltype.upper() in acceptedshells:
                print('\n' + ok, 'shell is set to {}'.format(Fore.LIGHTYELLOW_EX + shelltype.upper()))
                return shelltype
            else:
                print('\n' + err, 'please the type of shell you\'d like to use')
                print(err, 'example:' + Fore.LIGHTYELLOW_EX, 'cr0w >', Fore.LIGHTRED_EX + 'powershell/bash/zsh/nc...',
                      Style.RESET_ALL)
        except:
            print('\n\n' + err, 'exception caught! exiting...\n')
            sys.exit(1)


def showshelloutput():
    init()
    location = 'src/' + shelltype.lower()
    shell = open(location, 'r')
    shells = shell.readlines()
    print(ok, 'cooking some {}'.format(Fore.LIGHTRED_EX + shelltype.upper()), Style.RESET_ALL + 'shells!')
    cprint('\n*ding* *ding* *ding*\n', 'green', attrs=['bold', 'blink'])
    time.sleep(1)
    for sh in shells:
        print(ok, Fore.LIGHTYELLOW_EX + re.sub('TEMPHOST', lhost, sh).replace('TEMPPORT', lport))
    print(ok, 'thank you for using' + Fore.LIGHTMAGENTA_EX, 'inumaki!', Style.RESET_ALL + 'remember that in the '
                                                                                          'event of an absent '
                                                                                          'fully-tty shell, '
                                                                                          'you should '
                                                                                          'stabilize or spawn a '
                                                                                          'tty :)\n')


if __name__ == '__main__':
    clear()
    banner()
    inetfaces()
    submitlhost()
    submitlport()
    showcurrentconfig()
    gettypeofshell()
    showshelloutput()
